name: Deploy
on: push

jobs:
  linttestbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Install npm
        uses: actions/setup-npm
        with:
            node-version: 16
      - name: Install dependencies
        run: npm ci  
      - name: lint npm
        run: npm run lint 
      - name: test
        run: npm run test  
      - name: build
        run: npm run build